config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  resources :comments, only: [:destroy, :edit]

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

    root "home#index"

    get "/likes" => "likes#index", as: :user_likes

    get "/about" => 'home#about', as: :about

    get "/new" => 'posts#new', as: :new

    get "/contact_us" => "contact_us#new", as: :contact_us
    post "/contact_us"=> "contact_us#create"

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  validates :body, presence: true
  has_many :comments, dependent: :destroy
  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :users, through: :likes

  def like_for(user)
    likes.find_by_user_id(user)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.page params[:page]
  end

  def new
    # we need to define a new `Question` object in order to be able to
    # properly generate a form in Rails
    # Question is the ActiveRecord model
    @post = Post.new
  end

  def create
    @post       = Post.new(post_params)
    @post.user  = current_user
    if @post.save
      #render text: "SUCCESS"
      #render :show
      #redirect_to post_path({id: @post.id})
      #redirect_to post_path({@post.id})
      redirect_to posts_path, notice: "Post Created!"
    else
      # this will render `app/views/questions/new.html.erb` because the default
      # in this action is to render `app/views/questions/create.html.erb`
      flash[:alert] = "Post didn't save!"
      render :new
    end
  end

  # we receive a request such as : GET /questions/56
  # params[:id] will be `56`
  def show
    @post = Post.find params[:id]
    @like = @post.like_for(current_user)
    @comment = Comment.new
  end

  def edit
    redirect_to root_path, alert: "didn't say magic word" unless can? :edit, @post
  end

  def update
    redirect_to root_path, alert: "access denied" unless can? :update, @post
    if @post.update post_params
      redirect_to @post, notice: "Post Updated"
    else
      render :edit
    end
  end

  def destroy
    redirect_to root_path, alert: "uhhmmm, no access" unless can? :destroy, @post
      @post.destroy
      redirect_to posts_path, notice: "Post Gone"
  end

private

  def find_post
    @post = Post.find params[:id]
  end

  def post_params
    post_params = params.require(:post).permit([:title, :body])
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h1> EDIT Post </h1>

<%# this might not be defined in post controller %>
<%= @post.errors.full_messages.join(", ") %>

<%= form_for @post do |post| %>
  <div>
    <%= post.label :title %>
    <%= post.text_field :title %>
  </div>

  <div>
    <%= post.label :body %>
    <%= post.text_area :body %>
  </div>

  <%= post.submit %>
<% end %>

app/views/posts/index.html.erb
<h1> DEEZ R da POSTS : </h1>

<img src="https://s-media-cache-ak0.pinimg.com/736x/60/0d/12/600d12d40588f1ff8b459a092350433e.jpg"
style="width:304px;height:300px;float: right;">

<% @posts.each do |post| %>
  <div>
    <%= link_to post.title, post_path(post) %>
  </div>
<% end %>

<%= paginate @posts %>

app/views/posts/new.html.erb
<h1> New Post </h1>

<%= @post.errors.full_messages.join", " %>

<%= form_for @post do |post| %>
  <div>
    <%= post.label :title %>
    <%= post.text_field :title %>
  </div>

  <div>
    <%= post.label :body %>
    <%= post.text_area :body %>
  </div>
  <%= post.submit "Submit" %>

<% end %>

app/views/posts/show.html.erb
<h3> Post Content: </h3>
<h2> Title: <%= @post.title %></h2>
<p> <%= @post.body %> </p>
<p> <%= @post.created_at %> </p>

<% if @like.present? && @like.persisted? %>
  <%= link_to "Un-Like", post_like_path(@post, @like), method: :delete %>
<% else %>
  <%= link_to "Like", post_likes_path(@post), method: :post %>
<% end %>

<% if can? :edit, @post %>
  <%= link_to "Edit", edit_post_path(@post) %>
<% end %>
<% if can? :destroy, @post %>
  <%= link_to "Delete", post_path(@post),
                        method: :delete,
                        data: {confirm: "Are you sure?"} %>
<% end %>
<hr>

<h4>Add a Comment</h4>
<% if @comment.errors.any? %>
  <ul>
  <% @comment.errors.full_messages.each do |msg| %>
    <li><%= msg %><li>
  <% end %>
  </ul>
<% end %>

<%= form_for [@post, @comment] do |f| %>
<div>
  <%= f.label :body %>
  <%= f.text_area :body %>
</div>
  <%= f.submit %>
<% end %>

<hr>

<h2>Comments</h2>
<hr>
<% @post.comments.each do |comment| %>
  <p> <%= comment.body %> </p>

  <% if can? :edit, comment %>
    <%= link_to "Edit", edit_comment_path(comment) %>
  <% end %>

  <% if can? :destroy, comment %>
    <%= link_to "Delete", comment_path(comment),
                          method: :delete,
                          data: {confirm: "Are you sure?"} %>
  <% end %>

<% end %>